language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: AN8qB5VaI5qy5UNWgJGOz9UV1yCUrySG9swi/As/DpWbHmNzjL0pwJDkmowB0SW9UMX1fiNBvU7VWUwIPfcXpunAqdJiYo/gLJaFOcoQuSsv68nmUsx+18AYjMXeFXZ9eBVMs76pGqhtRH4qqYm7ww3l1kFs5vI0Zr7N8WOkSA2dnoKTTagZcjJo+INfpOtTojPylYV07dJnX6dHhj55yxa4eqBhoftTqAU9cligjebG8R6YV4AkWXCwLfeRoP7M64L1UMe9QQmzCcrM65dtGkWHw/+9ej0Iv2m4tkPn4PqM6Luowsq3gik4wb68WFfq73F9cS76lmdrjRG3F9bESJzOVbythEnPXN7PXaWQmZQTXjvMiIudd2aHe9Q4XOGFEAljQmQgobnTsxiQJouQ+qIC9Ra+IbQyACbFMuUSLbz/Bo+SgfBeWWMCE0Ea/XkcqNEyehMBH7opRdXPYDSdbhka8aepCzq5Yxlwbf2k8FEhIQ32i6+tBCVLH5Dy+C9RvoVWS1cgv7rmmUTZFoQKTgXEsmU0uutI+FCFj9CLwm1ZgiY8aucqw2Hly2S3bEZmB3DU6d4uNMZDr5rSbp0gQ/MWLZFwNWsMmCudq0Lz+Tm8XBppbtn+w2oHaJmZT5iGPHpcM0J2+AG7BP7jQ7Naov+1eU9KkW2obAzvkhQTIA4=
  - secure: hoCBBvSPM+8zx1Lo5jAwHPbcKti/EcPsE2bHqUIAUmTK8J1KiPwNPzq1V6CZAhhKDf4n0SYL4KnGjLhD9b39tWb/Y8ogQtaS6kinR9kL8wG30AWvdrHCrBS8kesoTXcN/GwzPH91Qyklz+9VfNd1F7xaGm5yCj4Dis2h7DBRyLKKlbXN5DQhA2LeV0lAG2LmgMbB/c6sdNLoISs/or4/RPlXZPVKbuKfxcPf2vTlC8xF0pW3y3OjssGukCyqsJm6C27Fp+NQkz4nbW77TUxfYiqaEYEr20lIMWNqrcTc2EP/33C/Do9E5dvgxBvjEpD1YWCsWyO1wQtp1Lc+NTtI77IuiFg/lISam64nDo7dlRjWqtQ4Ja08yd7jFy/zRIdXtnU3dxE7IQfz98w90EOxGKrMmf1zaNPeeiUL97ughlZ9dzBzi1uETUhJUSOHT/2atzk6xoboH73Vc1+WU7cxNMlyDosf1lYB1Ah3C9jULItKyxE57y1FadIj4wb4wqAr1JKvAWqk3QIOYvxw89oeYQMltBVr1Elq4ARFLEZbCD4S++byqZ6PNonVPjj2pcHyk2Cr+rb5QWMJJJJAnAskB0ICzuUE1+vcNQ14ZXZNY/THTH/Z2IY6LJjqQJH9/nz8NNnkB/dbk9T3ebZAXSIMoHWzoGGb/7vBAbDmLP61nNE=
  - secure: Z8A8Tqll8+/L6esWauGaMj9IU/7gOVgJBRSr0w0AR3N274QXNRHmqOp1FB+odwRvg4g+G1BW4T0BNUfhe2SkHMrsX1/fWhJsAj5dsgPEA+Y1Nbf3oVvQTaPJ4tqUxieG6dDJoXdhVZDF6GruX7IhPeb4xObw0YWZLV95X4uXzuDhYsi+fgRiQMce0ww4wtLclJXYmHnT0vBsVXgfkwvrQMgxHQbLdsKhSxi3BqVWk50d67xBlzegPmvivYIFnaF7MFxvZm3Jp9Lnwhrp/hew7OA0kTrBr4fApaC/D7qaOzSc77OkEL7EPWwhW0Eb/O7gwmSkdTzVcTsSttxRHTWLkSX6EhKx90gWBxEPV6y82ie/1eD4Qh/WI9QYEK+UzYl88/GyI0SolN2OxMPpiOqWg5ikysBJi9ctYoVi4sQjw9Rnoupvw0J43foDCJZ9EUtJRK7xfMB6S2Rr4nS9r+mZp2qOsXwLyb97hBEVuPFS8Yiy7bQ86WuIqNp/0FkJM90V1C/aIsj9KeAnmUm/1WGFVfVY2MXqj/0EPvBM6TShHUSrDZsr751Z2qGEvJSKUMFopZ/UffLdht68PnOe5/dn+6cS5/J8AmE1SVRx1YdEbzg3uBZFjYBKBsOc5q8GMTZYyXF07ps7utRLjH8aV7lHRnvsUtzzxeMrzkdVCgCh61Q=

before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
script:
- set -e
- bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
    - fiorenzino@gmail.com
    on_success: always
    on_failure: always