= Vert.x **J**son **P**ersistence API


This provides an asynchronous interface around a JDBC datasource to:

- create table

     jpaClient.create(CREATE_TABLE, result -> {});

- delete

     jpaClient.delete(TABLE, new JsonObject().put(KEY_TABLE, whiskyP.uuid), result_d -> {});

- merge

      connection.merge(TABLE, whiskyU.toJson(), new JsonObject().put(KEY_TABLE, whiskyU.uuid), result_m -> {});

- persist

      connection.persist(TABLE, whiskyP.toJson(), result_p -> {});

- query with named parameter

       connection.query("selct * from " + TABLE + " where name = :NAME ", new JsonObject().put("NAME", whiskyU.name),
                        result_q-> {});

- query with dynamic restrictions handler

 RestrinctionHandler<JsonObject, String, StringBuffer> rh = new RestrinctionHandler<JsonObject, String, StringBuffer>()
      {
         String alias = "a";
         String separator = " WHERE ";

         @Override public void handle(JsonObject params, String table, StringBuffer toSql)
         {
            toSql.append("select * from " + table + " " + alias + " ");
            if (params.getString("name") != null)
            {
               toSql.append(separator).append(alias).append(".name LIKE :name ");
               params.put("name", "%" + params.getString("name") + "%");
               separator = " and ";
            }
            if (params.getString("collection_name") != null)
            {
               toSql.append(separator).append(alias).append(".collection_name LIKE :collection_name ");
               params.put("collection_name", "%" + params.getString("collection_name") + "%");
               separator = " and ";
            }
            if (params.getString("uuid") != null)
            {
               toSql.append(separator).append(alias).append(".uuid = :uuid ");
               separator = " and ";
            }
         }
      };
      jpaClient.query(TABLE_NAME, params, rh, handler);


It's a vertx-jdbc clone with new Actions and some different methods:

- JPACreate
- JPADelete
- JPAHandlerQuery
- JPAMerge
- JPAPersist
- JPAQuery
- JPAStatementHelper


Also with rxActions inside!
